### ISSUE TITLE
NotSupportedError when purging completed tasks

### ISSUE THREAD

**Issue by svencan** [geekforbrains/django-workers#10]
The following line triggers a NotSupportedError from MySQLdb module:

https://github.com/geekforbrains/django-workers/blob/df7bac4b70fae212d7fe0ecb2589132b0e7b9cf7/workers/management/commands/runworkers.py#L72

Full trace:

`(whitehouse) sven@postbox:~/projects/alr-whitehouse$ python manage.py runworkers
Traceback (most recent call last):
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.NotSupportedError: (1235, "This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/workers/management/commands/runworkers.py", line 72, in handle
    Task.objects.exclude(pk__in=keep).filter(status=Task.COMPLETED).delete()
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/models/query.py", line 711, in delete
    deleted, _rows_count = collector.delete()
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/models/deletion.py", line 294, in delete
    count = qs._raw_delete(using=self.using)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/models/query.py", line 725, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/sven/venvs/whitehouse/lib/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
django.db.utils.NotSupportedError: (1235, "This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'")`

**Comment by svencan** [comment]
The workaround I use for now is to set `WORKERS_PURGE = 0` and to delete completed tasks by a cutstom command.

**Comment by Dbof** [comment]
Same problem with MongoDB and [`djongo`](https://github.com/nesdis/djongo) package. My current solution is to invert the sorting done by `django-workers` and do this in a predefined schedule:

```python
@task(schedule=60*60*24)  # Every 24 hours
def purge_djongo():
    if not hasattr(settings, 'WORKERS_PURGE_DJONGO') or type(settings.WORKERS_PURGE_DJONGO) is not int or settings.WORKERS_PURGE_DJONGO <= 0:
        # do not purge using this approach
        return

    keep = (
        Task.objects.filter(status=Task.COMPLETED)
        .order_by('completed_at')
        .order_by('run_at')[settings.WORKERS_PURGE_DJONGO:]
    )
    if keep:
        keep.delete()
```

This seems to work for my use case. Maybe use the same approach in https://github.com/geekforbrains/django-workers/blob/master/workers/management/commands/runworkers.py ?
